"""Email a news digest — the desk's own reading, in their inbox.

SMTP settings come from the environment (``PULSE_SMTP_*``); nothing is read from a file
checked into the repo, and a blank user/password simply DISABLES email — search keeps
working, and every route says plainly that email is not configured rather than failing in
a way that reads like a bug.

Ported from the desk's atlas_serve.py, including the two details that took a real outage
to learn: the envelope-from must be a bare address (Brevo and other relays reject a
display-name string there) while the header From may carry the friendly name, and every
message goes out as BOTH plain text and HTML so a text-only client is not handed markup.
"""

from __future__ import annotations

import html as _html
import re
import smtplib
import ssl
from dataclasses import dataclass
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr, parseaddr
from typing import Any

from evam_backend_core.logging import get_logger

log = get_logger("pulse.mailer")

_SEV_COLOR = {"GOOD": "#2E7D4F", "BAD": "#C98A1B", "UGLY": "#B3432B",
               "POLICY": "#1F6FA8"}


@dataclass(frozen=True)
class SmtpConfig:
    host: str = ""
    port: int = 587
    user: str = ""
    password: str = ""
    sender: str = ""
    from_name: str = ""

    @property
    def ready(self) -> bool:
        """Email is OFF unless a host, a login and a key are all present. Half-configured
        is treated as off, not as an error to discover at send time."""
        return bool(self.host and self.user and self.password)


def digest_html(term: str, articles: list[dict[str, Any]],
                dfrom: str = "", dto: str = "") -> str:
    """One term's articles as an email table — severity chip, headline linked to its
    source, and the source/via/date line underneath."""
    span = f"{dfrom} to {dto}" if dfrom or dto else "last 3 months"
    rows = []
    for a in articles:
        colour = _SEV_COLOR.get(a.get("severity", "GOOD"), "#2E7D4F")
        rows.append(
            '<tr><td style="padding:8px 10px;border-bottom:1px solid #eee;vertical-align:top">'
            f'<span style="background:{colour};color:#fff;font-size:11px;font-weight:700;'
            f'padding:2px 8px;border-radius:10px">{_html.escape(a.get("severity", ""))}</span></td>'
            '<td style="padding:8px 10px;border-bottom:1px solid #eee">'
            f'<a href="{_html.escape(a.get("url", ""))}" '
            'style="color:#1B2A4A;text-decoration:none;font-weight:600">'
            f'{_html.escape(a.get("title", ""))}</a>'
            '<div style="color:#5F6E76;font-size:12px;margin-top:2px">'
            f'{_html.escape(a.get("source", ""))} &middot; {_html.escape(a.get("via", ""))}'
            f' &middot; {_html.escape(a.get("when", ""))}</div></td></tr>')
    body = "".join(rows) or ('<tr><td style="padding:14px;color:#5F6E76">'
                             'No articles in this window.</td></tr>')
    return (
        '<div style="font-family:Segoe UI,Arial,sans-serif;max-width:720px;margin:auto">'
        '<div style="background:#1B2A4A;color:#fff;padding:16px 18px;border-radius:10px 10px 0 0">'
        '<b style="font-size:17px">EVAM PRISM &middot; News digest</b><br>'
        f'<span style="color:#9FB3BA;font-size:13px">{_html.escape(term)} &middot; {span}'
        f' &middot; {len(articles)} articles</span></div>'
        f'<table style="width:100%;border-collapse:collapse;background:#fff">{body}</table>'
        '<div style="color:#8a97a0;font-size:11px;padding:12px 4px">Generated by the PRISM '
        'News Radar. Every article links to its source.</div></div>')


def send_email(cfg: SmtpConfig, recipients: list[str], subject: str,
               html_body: str) -> tuple[bool, str]:
    """Blocking on purpose — callers run it in a threadpool. Returns (ok, message) where
    the message is written to be shown to the person who asked, not only logged."""
    if not cfg.ready:
        return False, ("Email is not configured — set PULSE_SMTP_HOST / _USER / _PASS "
                       "(search works without it).")
    recipients = [r.strip() for r in recipients if r and r.strip()]
    if not recipients:
        return False, "No valid recipients."

    sender = cfg.sender or cfg.user
    # The envelope sender must be a BARE address: several relays (Brevo among them)
    # reject a display-name string here even though the header From accepts one.
    envelope_from = parseaddr(sender)[1] or sender
    header_from = (formataddr((cfg.from_name, envelope_from))
                   if cfg.from_name and "<" not in sender else sender)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = header_from
    msg["To"] = ", ".join(recipients)
    # Text part first: a client that prefers plain text must not be handed raw markup.
    msg.attach(MIMEText(re.sub("<[^>]+>", "", html_body), "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    log.info("pulse_email_sending", extra={"subject": subject, "host": cfg.host,
                                           "port": cfg.port, "recipients": len(recipients)})
    try:
        if cfg.port == 465:
            with smtplib.SMTP_SSL(cfg.host, cfg.port,
                                  context=ssl.create_default_context(), timeout=20) as s:
                s.login(cfg.user, cfg.password)
                s.sendmail(envelope_from, recipients, msg.as_string())
        else:
            with smtplib.SMTP(cfg.host, cfg.port, timeout=20) as s:
                s.starttls(context=ssl.create_default_context())
                s.login(cfg.user, cfg.password)
                s.sendmail(envelope_from, recipients, msg.as_string())
    except Exception as exc:  # noqa: BLE001 - reported to the caller, never raised at them
        log.error("pulse_email_failed", extra={"host": cfg.host, "port": cfg.port,
                                               "user": cfg.user, "error": str(exc)})
        return False, f"Send failed: {exc}"
    log.info("pulse_email_sent", extra={"recipients": len(recipients)})
    return True, f"Sent to {len(recipients)} recipient(s)."
