{{- $needDb := not .Values.database.existingSecret }}
{{- $needApi := not .Values.apiKeys.existingSecret }}
{{- if or $needDb $needApi }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "access.secretName" . }}
  labels:
    {{- include "access.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needDb }}
  db-password: {{ .Values.database.password | quote }}
  {{- end }}
  {{- if $needApi }}
  api-keys: {{ .Values.apiKeys.value | quote }}
  {{- end }}
{{- end }}
