"""Covenant monitoring — definitions, recurring observations, results, waivers.

The model splits configuration from observation:

* ``covenants`` (this module's CRUD) — the DEFINITION: what is tested (a financial
  metric against a threshold, or a reporting/security obligation), how often, from when,
  and how severe a breach is.
* ``monitoring_reporting`` (PRISM master table 7) — the OBSERVATIONS: one row per
  period, generated by the recurring sweep with ``record_type='Covenant'`` and
  ``details.covenant_id``. A partial UNIQUE index makes generation idempotent per
  (covenant, due date) — a sweep retry can never double-generate a period.

The lifecycle of one observation:

    Pending ──(result: passes)──▶ Compliant
            ──(result: fails)───▶ Breached ──(waive, decision-backed)──▶ Waived
            ──(due date + grace lapses unsubmitted)──▶ Overdue
    Waived  ──(waiver_valid_until lapses)──▶ Breached again (waiver_status='Expired')

* A BREACH (or an expired waiver) auto-opens an EWS case — deduped by source, so a
  re-submitted result or a sweep retry can never spawn a duplicate case.
* A WAIVER takes effect only against a durable ``kind="waiver"`` decision (senior credit
  authority, subject-bound to the observation, MANDATORY validity window) recorded on
  the single-winner decision store FIRST — the endpoint verifies the record, never a
  client field.

    POST /v1/covenants                         define a covenant
    GET  /v1/covenants?entity_id=…             a company's covenant register
    PATCH /v1/covenants/{id}                   amend threshold / schedule / active flag
    POST /v1/monitoring/{id}/result            submit a period's actual (computes breach)
    POST /v1/monitoring/{id}/waive             apply a verified, time-boxed waiver
    POST /v1/internal/covenants/run-sweep      generate + overdue + waiver-expiry (service)
"""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime, timedelta
from typing import Any

from fastapi import Depends
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import select, text
from sqlalchemy.dialects.postgresql import insert as pg_insert

from app.api.custom import _ensure_company_read
from app.authz import engine as authz
from app.authz.engine import service_ctx
from app.core.errors import ConflictError, ForbiddenError, NotFoundError, ValidationAppError
from app.core.logging import request_id_ctx
from app.core.router import api_router
from app.core.security import RequestContext, get_context
from app.db.base import AuditLog
from app.models.covenants import Covenant, EwsCase
from app.models.decisions import WorkflowDecision
from app.models.prism import MonitoringReporting
from app.repositories.subjects import load_subject

router = api_router()

_SWEEP_SERVICES = {"svc_workflows"}
_WAIVER_AUTHORITY = {"Credit Head", "Management", "Admin", "LMS Management"}

_FREQUENCY_MONTHS = {"Monthly": 1, "Quarterly": 3, "SemiAnnual": 6, "Annual": 12}


class CovenantIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    entity_id: uuid.UUID
    deal_id: uuid.UUID | None = None
    lending_id: uuid.UUID | None = None
    name: str = Field(min_length=1, max_length=200)
    covenant_type: str = Field(default="Financial",
                               pattern="^(Financial|Reporting|Security|Other)$")
    description: str | None = Field(default=None, max_length=4000)
    metric: str | None = Field(default=None, max_length=60)      # e.g. "dscr"
    operator: str | None = Field(default=None, pattern="^(>=|<=|>|<|=)$")
    threshold: float | None = None
    frequency: str = Field(default="Quarterly",
                           pattern="^(OneTime|Monthly|Quarterly|SemiAnnual|Annual)$")
    first_due_on: date
    grace_days: int = Field(default=0, ge=0, le=365)
    breach_severity: str = Field(default="Amber", pattern="^(Amber|Red)$")


class CovenantUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")
    description: str | None = Field(default=None, max_length=4000)
    threshold: float | None = None
    grace_days: int | None = Field(default=None, ge=0, le=365)
    breach_severity: str | None = Field(default=None, pattern="^(Amber|Red)$")
    is_active: bool | None = None


class ResultIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    # The tested value for a FINANCIAL covenant; a reporting/security obligation submits
    # without one (the submission itself is the compliance).
    actual_value: float | None = None
    submitted_on: date | None = None
    note: str | None = Field(default=None, max_length=4000)


class WaiveIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    # The durable waiver decision (kind="waiver") this waiver is backed by.
    decision_ref: str = Field(min_length=1, max_length=200)
    note: str | None = Field(default=None, max_length=4000)


class SweepIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    # How far ahead observations are generated.
    horizon_days: int = Field(default=30, ge=0, le=400)
    limit: int = Field(default=500, ge=1, le=2000)


def _require_manage(ctx: RequestContext) -> None:
    authz.enforce_operation(ctx.user, "manage_covenants")


def _serialize(c: Covenant) -> dict[str, Any]:
    return {"id": str(c.id), "entity_id": str(c.entity_id),
            "deal_id": str(c.deal_id) if c.deal_id else None,
            "lending_id": str(c.lending_id) if c.lending_id else None,
            "name": c.name, "covenant_type": c.covenant_type,
            "description": c.description, "metric": c.metric, "operator": c.operator,
            "threshold": float(c.threshold) if c.threshold is not None else None,
            "frequency": c.frequency,
            "first_due_on": c.first_due_on.isoformat() if c.first_due_on else None,
            "grace_days": c.grace_days, "breach_severity": c.breach_severity,
            "is_active": c.is_active, "version": c.version}


def _serialize_obs(m: MonitoringReporting) -> dict[str, Any]:
    return {"id": str(m.id), "entity_id": str(m.entity_id),
            "deal_id": str(m.deal_id) if m.deal_id else None,
            "record_type": m.record_type, "covenant_name": m.covenant_name,
            "due_date": m.due_date.isoformat() if m.due_date else None,
            "submitted_date": m.submitted_date.isoformat() if m.submitted_date else None,
            "on_time": m.on_time, "delay_days": m.delay_days, "period": m.period,
            "status": m.status,
            "target_value": float(m.target_value) if m.target_value is not None else None,
            "actual_value": float(m.actual_value) if m.actual_value is not None else None,
            "breached": m.breached, "waiver_status": m.waiver_status,
            "waiver_valid_until": (m.waiver_valid_until.isoformat()
                                   if m.waiver_valid_until else None),
            "waiver_decision_ref": m.waiver_decision_ref,
            "details": m.details}


def add_months(d: date, months: int) -> date:
    """Month arithmetic with day clamping (Jan 31 + 1 month → Feb 28) — schedule
    projection must never skip or crash on short months."""
    total = (d.year * 12 + (d.month - 1)) + months
    year, month = divmod(total, 12)
    month += 1
    for day in (d.day, 30, 29, 28):
        try:
            return date(year, month, day)
        except ValueError:
            continue
    raise ValueError(f"cannot add {months} months to {d}")  # pragma: no cover


def due_dates(first_due_on: date, frequency: str, horizon: date,
              cap: int = 400) -> list[date]:
    """Every due date of the schedule up to (and including) ``horizon``. OneTime yields
    at most its single date; recurring schedules are bounded by ``cap`` periods."""
    if first_due_on > horizon:
        return []
    step = _FREQUENCY_MONTHS.get(frequency)
    if step is None:                       # OneTime
        return [first_due_on]
    out: list[date] = []
    for k in range(cap):
        due = add_months(first_due_on, step * k)
        if due > horizon:
            break
        out.append(due)
    return out


def breach_test(operator: str, threshold: float, actual: float) -> bool:
    """True = BREACHED (the covenant test FAILED)."""
    ok = {">=": actual >= threshold, "<=": actual <= threshold,
          ">": actual > threshold, "<": actual < threshold,
          "=": actual == threshold}[operator]
    return not ok


async def _open_ews_case(ctx: RequestContext, *, entity_id: uuid.UUID,
                         deal_id: uuid.UUID | None, source: str, source_ref: str,
                         severity: str, title: str, summary: str | None) -> str | None:
    """Open (or attach to) the EWS case for a trigger source — idempotent at the database
    (UNIQUE (tenant, source, source_ref)), so a re-submitted result or a sweep retry can
    never spawn a duplicate case. Returns the case id (existing or new)."""
    won = (await ctx.session.execute(
        pg_insert(EwsCase).values(
            tenant_id=ctx.tenant_id, entity_id=entity_id, deal_id=deal_id,
            source=source, source_ref=source_ref, severity=severity, title=title,
            summary=summary, status="Open", opened_by=ctx.actor, created_by=ctx.actor)
        .on_conflict_do_nothing(constraint="ews_cases_source_dedupe")
        .returning(EwsCase.id))).scalar_one_or_none()
    if won is not None:
        ctx.session.add(AuditLog(
            tenant_id=ctx.tenant_id, actor=ctx.actor, action="ews.open",
            resource_type="ews_cases", resource_id=str(won),
            request_id=request_id_ctx.get(),
            changes={"source": source, "source_ref": source_ref, "severity": severity}))
        return str(won)
    existing = (await ctx.session.execute(
        select(EwsCase.id).where(
            EwsCase.tenant_id == ctx.tenant_id, EwsCase.source == source,
            EwsCase.source_ref == source_ref))).scalar_one_or_none()
    return str(existing) if existing else None


# --------------------------------------------------------------------------- #
# Definitions
# --------------------------------------------------------------------------- #
@router.post("/v1/covenants", tags=["Covenants"], status_code=201,
             summary="Define a covenant (schedule + test)")
async def create_covenant(payload: CovenantIn,
                          ctx: RequestContext = Depends(get_context)) -> dict[str, Any]:
    _require_manage(ctx)
    if payload.covenant_type == "Financial" and not (
            payload.metric and payload.operator and payload.threshold is not None):
        raise ValidationAppError(
            "A Financial covenant needs metric + operator + threshold "
            "(e.g. dscr >= 1.20).")
    if await load_subject(ctx.session, ctx.tenant_id, "Entity", payload.entity_id) is None:
        raise NotFoundError(f"Entity '{payload.entity_id}' not found.")
    if payload.deal_id is not None and await load_subject(
            ctx.session, ctx.tenant_id, "Deal", payload.deal_id) is None:
        raise NotFoundError(f"Deal '{payload.deal_id}' not found.")
    row = Covenant(tenant_id=ctx.tenant_id, created_by=ctx.actor,
                   **payload.model_dump())
    ctx.session.add(row)
    await ctx.session.flush()
    await ctx.session.refresh(row)
    return _serialize(row)


@router.get("/v1/covenants", tags=["Covenants"],
            summary="A company's covenant register")
async def list_covenants(entity_id: uuid.UUID,
                         ctx: RequestContext = Depends(get_context),
                         deal_id: uuid.UUID | None = None,
                         active_only: bool = True) -> dict[str, Any]:
    await _ensure_company_read(ctx, entity_id)
    conds = [Covenant.tenant_id == ctx.tenant_id, Covenant.entity_id == entity_id,
             Covenant.deleted_at.is_(None)]
    if deal_id is not None:
        conds.append(Covenant.deal_id == deal_id)
    if active_only:
        conds.append(Covenant.is_active.is_(True))
    rows = list((await ctx.session.execute(
        select(Covenant).where(*conds).order_by(Covenant.name))).scalars())
    return {"items": [_serialize(r) for r in rows]}


@router.get("/v1/covenants/observations", tags=["Covenants"],
            summary="A company's covenant OBSERVATIONS (the periods), newest due first")
async def list_observations(entity_id: uuid.UUID,
                            ctx: RequestContext = Depends(get_context),
                            lending_id: uuid.UUID | None = None,
                            status: str | None = None,
                            limit: int = 200) -> dict[str, Any]:
    """The LMS covenant tab's read: every generated period for the company's covenants —
    Pending, Compliant, Breached, Waived, Overdue — with the covenant id in details so
    the UI can pair observation to definition. Company-read gated like the register."""
    await _ensure_company_read(ctx, entity_id)
    conds = [MonitoringReporting.tenant_id == ctx.tenant_id,
             MonitoringReporting.entity_id == entity_id,
             MonitoringReporting.record_type == "Covenant",
             MonitoringReporting.deleted_at.is_(None)]
    if status is not None:
        conds.append(MonitoringReporting.status == status)
    rows = list((await ctx.session.execute(
        select(MonitoringReporting).where(*conds)
        .order_by(MonitoringReporting.due_date.desc().nulls_last())
        .limit(min(max(limit, 1), 500)))).scalars())
    if lending_id is not None:
        rows = [r for r in rows
                if (r.details or {}).get("lending_id") == str(lending_id)]
    return {"items": [_serialize_obs(r) for r in rows]}


@router.get("/v1/covenants/{covenant_id}", tags=["Covenants"], summary="One covenant")
async def get_covenant(covenant_id: uuid.UUID,
                       ctx: RequestContext = Depends(get_context)) -> dict[str, Any]:
    row = await _covenant(ctx, covenant_id)
    await _ensure_company_read(ctx, row.entity_id)
    return _serialize(row)


@router.patch("/v1/covenants/{covenant_id}", tags=["Covenants"],
              summary="Amend a covenant (threshold / grace / severity / active)")
async def update_covenant(covenant_id: uuid.UUID, payload: CovenantUpdate,
                          ctx: RequestContext = Depends(get_context)) -> dict[str, Any]:
    _require_manage(ctx)
    row = await _covenant(ctx, covenant_id)
    changes = payload.model_dump(exclude_unset=True)
    if not changes:
        raise ValidationAppError("Nothing to update.")
    before = {k: getattr(row, k) for k in changes}
    for k, v in changes.items():
        setattr(row, k, v)
    row.updated_by = ctx.actor
    row.version = (row.version or 1) + 1
    ctx.session.add(AuditLog(
        tenant_id=ctx.tenant_id, actor=ctx.actor, action="covenant.update",
        resource_type="covenants", resource_id=str(row.id),
        request_id=request_id_ctx.get(),
        changes={"before": {k: str(v) for k, v in before.items()},
                 "after": {k: str(v) for k, v in changes.items()}}))
    await ctx.session.flush()
    await ctx.session.refresh(row)
    return _serialize(row)


async def _covenant(ctx: RequestContext, covenant_id: uuid.UUID) -> Covenant:
    row = (await ctx.session.execute(
        select(Covenant).where(
            Covenant.tenant_id == ctx.tenant_id, Covenant.id == covenant_id,
            Covenant.deleted_at.is_(None)))).scalar_one_or_none()
    if row is None:
        raise NotFoundError(f"No covenant '{covenant_id}'.")
    return row


async def _observation(ctx: RequestContext,
                       monitoring_id: uuid.UUID) -> MonitoringReporting:
    row = (await ctx.session.execute(
        select(MonitoringReporting).where(
            MonitoringReporting.tenant_id == ctx.tenant_id,
            MonitoringReporting.id == monitoring_id,
            MonitoringReporting.deleted_at.is_(None)))).scalar_one_or_none()
    if row is None:
        raise NotFoundError(f"No monitoring record '{monitoring_id}'.")
    if row.record_type != "Covenant":
        raise ValidationAppError(
            f"Monitoring record '{monitoring_id}' is {row.record_type!r}, not a "
            "covenant observation.")
    return row


# --------------------------------------------------------------------------- #
# Results
# --------------------------------------------------------------------------- #
@router.post("/v1/monitoring/{monitoring_id}/result", tags=["Covenants"],
             summary="Submit a covenant period's result (computes breach)")
async def submit_result(monitoring_id: uuid.UUID, payload: ResultIn,
                        ctx: RequestContext = Depends(get_context)) -> dict[str, Any]:
    _require_manage(ctx)
    row = await _observation(ctx, monitoring_id)
    if row.status in ("Compliant", "Breached", "Waived"):
        raise ConflictError(
            f"Observation already has a result ({row.status}); a corrected figure is a "
            "governance event — waive or escalate, never overwrite.")
    details = dict(row.details or {})
    operator, threshold = details.get("operator"), row.target_value
    submitted = payload.submitted_on or datetime.now(UTC).date()
    row.submitted_date = submitted
    if row.due_date is not None:
        row.on_time = submitted <= row.due_date
        row.delay_days = max((submitted - row.due_date).days, 0)
    breached = False
    if operator and threshold is not None:
        if payload.actual_value is None:
            raise ValidationAppError(
                "This is a FINANCIAL covenant observation — actual_value is required.")
        row.actual_value = payload.actual_value
        breached = breach_test(str(operator), float(threshold), payload.actual_value)
    row.breached = breached
    row.status = "Breached" if breached else "Compliant"
    if payload.note:
        details["result_note"] = payload.note
        row.details = details
    row.updated_by = ctx.actor
    row.version = (row.version or 1) + 1
    ctx.session.add(AuditLog(
        tenant_id=ctx.tenant_id, actor=ctx.actor, action="covenant.result",
        resource_type="monitoring_reporting", resource_id=str(row.id),
        request_id=request_id_ctx.get(),
        changes={"actual_value": payload.actual_value, "breached": breached,
                 "covenant": row.covenant_name}))
    case_id = None
    if breached:
        # A breach IS an early-warning trigger — the case opens in the SAME transaction
        # as the result, so a recorded breach can never silently lack its case.
        case_id = await _open_ews_case(
            ctx, entity_id=row.entity_id, deal_id=row.deal_id,
            source="covenant", source_ref=str(row.id),
            severity=str(details.get("breach_severity") or "Amber"),
            title=f"Covenant breach — {row.covenant_name}",
            summary=(f"{details.get('metric')} {operator} {threshold} tested at "
                     f"{payload.actual_value} for period {row.period}"))
    await ctx.session.flush()
    await ctx.session.refresh(row)
    return {**_serialize_obs(row), "ews_case_id": case_id}


# --------------------------------------------------------------------------- #
# Waivers — decision-backed, time-boxed
# --------------------------------------------------------------------------- #
@router.post("/v1/monitoring/{monitoring_id}/waive", tags=["Covenants"],
             summary="Apply a verified, time-boxed covenant waiver")
async def waive_breach(monitoring_id: uuid.UUID, payload: WaiveIn,
                       ctx: RequestContext = Depends(get_context)) -> dict[str, Any]:
    _require_manage(ctx)
    row = await _observation(ctx, monitoring_id)
    if not row.breached or row.status not in ("Breached",):
        raise ConflictError(
            f"Observation is {row.status!r}; only a live Breached observation can be "
            "waived.")
    # VERIFY the durable waiver decision — subject-bound, Approved, senior authority,
    # with a MANDATORY validity window. The waiver takes effect from the RECORD, never
    # from the caller's say-so.
    dec = (await ctx.session.execute(
        select(WorkflowDecision).where(
            WorkflowDecision.tenant_id == ctx.tenant_id,
            WorkflowDecision.workflow_id == payload.decision_ref))).scalar_one_or_none()
    if dec is None:
        raise ValidationAppError(
            f"No decision recorded under reference '{payload.decision_ref}'.")
    if dec.subject_type != "Monitoring" or str(dec.subject_id) != str(row.id):
        raise ValidationAppError(
            "The referenced decision is not a waiver for THIS observation.")
    if dec.decision != "Approved":
        raise ValidationAppError(
            f"The referenced decision is {dec.decision!r} — only an Approved waiver "
            "decision can excuse a breach.")
    from evam_backend_core.rbac_catalog import canonical_roles
    if not (canonical_roles(dec.roles) & _WAIVER_AUTHORITY):
        raise ForbiddenError(
            "The referenced decision was not made with senior credit authority "
            f"(one of {sorted(_WAIVER_AUTHORITY)}).")
    if not dec.valid_days:
        raise ValidationAppError(
            "A waiver must be TIME-BOXED — the decision carries no valid_days.")
    row.waiver_status = "Granted"
    row.waiver_decision_ref = payload.decision_ref
    row.waiver_valid_until = datetime.now(UTC).date() + timedelta(days=dec.valid_days)
    row.waiver_note = payload.note or dec.note
    row.status = "Waived"
    row.updated_by = ctx.actor
    row.version = (row.version or 1) + 1
    ctx.session.add(AuditLog(
        tenant_id=ctx.tenant_id, actor=ctx.actor, action="covenant.waive",
        resource_type="monitoring_reporting", resource_id=str(row.id),
        request_id=request_id_ctx.get(),
        changes={"decision_ref": payload.decision_ref, "granted_by": dec.decided_by,
                 "valid_until": row.waiver_valid_until.isoformat()}))
    await ctx.session.flush()
    await ctx.session.refresh(row)
    return _serialize_obs(row)


# --------------------------------------------------------------------------- #
# The recurring sweep (service): generate + overdue + waiver expiry
# --------------------------------------------------------------------------- #
@router.post("/v1/internal/covenants/run-sweep", tags=["Internal"],
             summary="Covenant sweep: generate due observations, mark overdue, expire "
                     "lapsed waivers (idempotent)")
async def run_sweep(payload: SweepIn,
                    ctx: RequestContext = Depends(get_context)) -> dict[str, Any]:
    if service_ctx.get() not in _SWEEP_SERVICES:
        raise ForbiddenError(
            "The covenant sweep runs under the workflow service principal only.")
    today = datetime.now(UTC).date()
    horizon = today + timedelta(days=payload.horizon_days)

    # 1. GENERATE the schedule's observations up to the horizon. The partial unique
    #    index absorbs everything already generated — replay-safe by construction.
    covenants = list((await ctx.session.execute(
        select(Covenant).where(
            Covenant.tenant_id == ctx.tenant_id, Covenant.is_active.is_(True),
            Covenant.deleted_at.is_(None)))).scalars())
    generated = 0
    for cov in covenants:
        if cov.first_due_on is None:      # deferred — stamps at first disbursement
            continue
        for due in due_dates(cov.first_due_on, cov.frequency, horizon):
            won = (await ctx.session.execute(
                pg_insert(MonitoringReporting).values(
                    tenant_id=ctx.tenant_id, entity_id=cov.entity_id,
                    deal_id=cov.deal_id, record_type="Covenant",
                    covenant_name=cov.name, due_date=due, period=due.isoformat(),
                    status="Pending", target_value=cov.threshold,
                    details={"covenant_id": str(cov.id), "metric": cov.metric,
                             "operator": cov.operator,
                             "breach_severity": cov.breach_severity,
                             "grace_days": cov.grace_days,
                             "lending_id": str(cov.lending_id) if cov.lending_id
                             else None},
                    created_by=ctx.actor)
                # Bare ON CONFLICT DO NOTHING: the only unique constraint these values
                # can hit is the partial covenant-period index, and "already generated"
                # is exactly the no-op we want — replay-safe by construction.
                .on_conflict_do_nothing()
                .returning(MonitoringReporting.id))).scalar_one_or_none()
            if won is not None:
                generated += 1

    # 2. NEWLY OVERDUE: due + grace lapsed with nothing submitted. The status flip makes
    #    this report-once (an already-Overdue row no longer matches).
    overdue_rows = (await ctx.session.execute(text(
        "UPDATE monitoring_reporting SET status = 'Overdue', on_time = false, "
        "delay_days = (:today - due_date), updated_by = :actor "
        "WHERE tenant_id = :tid AND deleted_at IS NULL AND record_type = 'Covenant' "
        "AND submitted_date IS NULL AND status = 'Pending' "
        "AND due_date + COALESCE((details->>'grace_days')::int, 0) < :today "
        "RETURNING id, covenant_name, due_date, entity_id, deal_id, period"),
        {"today": today, "actor": ctx.actor,
         "tid": str(ctx.tenant_id)})).mappings().all()

    # 3. LAPSED WAIVERS: the excuse expires, the breach is LIVE again, and a fresh EWS
    #    case opens (deduped per observation under the waiver_expiry source).
    expired_rows = (await ctx.session.execute(text(
        "UPDATE monitoring_reporting SET waiver_status = 'Expired', "
        "status = 'Breached', updated_by = :actor "
        "WHERE tenant_id = :tid AND deleted_at IS NULL AND record_type = 'Covenant' "
        "AND waiver_status = 'Granted' AND waiver_valid_until < :today "
        "RETURNING id, covenant_name, due_date, entity_id, deal_id, period, "
        "waiver_decision_ref"),
        {"today": today, "actor": ctx.actor,
         "tid": str(ctx.tenant_id)})).mappings().all()
    for r in expired_rows:
        await _open_ews_case(
            ctx, entity_id=r["entity_id"], deal_id=r["deal_id"],
            source="waiver_expiry", source_ref=str(r["id"]), severity="Red",
            title=f"Waiver expired — {r['covenant_name']}",
            summary=(f"The waiver ({r['waiver_decision_ref']}) on period "
                     f"{r['period']} lapsed; the breach is live again."))
        ctx.session.add(AuditLog(
            tenant_id=ctx.tenant_id, actor=ctx.actor, action="covenant.waiver_expired",
            resource_type="monitoring_reporting", resource_id=str(r["id"]),
            request_id=request_id_ctx.get(),
            changes={"covenant": r["covenant_name"],
                     "decision_ref": r["waiver_decision_ref"]}))

    def _dump(r: Any) -> dict[str, Any]:
        return {"id": str(r["id"]), "covenant_name": r["covenant_name"],
                "due_date": r["due_date"].isoformat() if r["due_date"] else None,
                "entity_id": str(r["entity_id"]),
                "deal_id": str(r["deal_id"]) if r["deal_id"] else None,
                "period": r["period"]}

    return {"swept_on": today.isoformat(), "generated": generated,
            "overdue": [_dump(r) for r in overdue_rows[:payload.limit]],
            "waivers_expired": [_dump(r) for r in expired_rows[:payload.limit]]}
