"""initial Register schema — PRISM 7 master tables + ATLAS operational tables

Revision ID: 0001
Revises:
Create Date: 2026-07-24

This is the authoritative DDL for the Register. It is deliberately hand-written (rather
than autogenerated) so the constraints, indexes, triggers and row-level-security
policies that make the Register a *stable source of truth* are explicit and reviewable.
"""
from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


# Every business table shares these trailing columns (tenant/version/audit/soft-delete).
COMMON = """
    tenant_id      uuid        NOT NULL,
    version        integer     NOT NULL DEFAULT 1,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    created_by     varchar(120),
    updated_by     varchar(120),
    deleted_at     timestamptz
"""


def _table(name: str, columns: str) -> None:
    op.execute(
        f"""
        CREATE TABLE {name} (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            {columns},
            {COMMON}
        );
        """
    )
    # Auto-maintain updated_at on every UPDATE.
    op.execute(
        f"""
        CREATE TRIGGER trg_{name}_updated_at BEFORE UPDATE ON {name}
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )
    op.execute(f"CREATE INDEX ix_{name}_tenant ON {name} (tenant_id);")
    op.execute(f"CREATE INDEX ix_{name}_tenant_active ON {name} (tenant_id) WHERE deleted_at IS NULL;")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")   # gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")    # trigram search indexes

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # --- system tables ---------------------------------------------------
    op.execute(
        """
        CREATE TABLE tenants (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            code varchar(40) NOT NULL UNIQUE,
            name varchar(200) NOT NULL,
            is_active boolean NOT NULL DEFAULT true,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            created_by varchar(120),
            updated_by varchar(120)
        );
        """
    )
    op.execute(
        """
        CREATE TABLE tenant_settings (
            tenant_id uuid PRIMARY KEY,
            settings jsonb NOT NULL DEFAULT '{}',
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            created_by varchar(120),
            updated_by varchar(120)
        );
        """
    )
    op.execute(
        """
        CREATE TABLE ref_values (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            category varchar(60) NOT NULL,
            value varchar(120) NOT NULL,
            label varchar(160),
            sort_order integer NOT NULL DEFAULT 0,
            is_active boolean NOT NULL DEFAULT true,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            created_by varchar(120),
            updated_by varchar(120),
            CONSTRAINT ref_values_category_value UNIQUE (category, value)
        );
        CREATE INDEX ix_ref_values_category ON ref_values (category);
        """
    )
    op.execute(
        """
        CREATE TABLE idempotency_keys (
            tenant_id uuid NOT NULL,
            key varchar(200) NOT NULL,
            request_hash varchar(64) NOT NULL,
            method varchar(10) NOT NULL,
            path varchar(300) NOT NULL,
            status_code integer NOT NULL,
            response_body jsonb,
            created_at timestamptz NOT NULL DEFAULT now(),
            expires_at timestamptz NOT NULL,
            PRIMARY KEY (tenant_id, key)
        );
        CREATE INDEX ix_idempotency_expires ON idempotency_keys (expires_at);
        """
    )
    op.execute(
        """
        CREATE TABLE audit_log (
            id bigserial PRIMARY KEY,
            tenant_id uuid,
            at timestamptz NOT NULL DEFAULT now(),
            actor varchar(120),
            action varchar(40) NOT NULL,
            resource_type varchar(60),
            resource_id varchar(64),
            request_id varchar(64),
            changes jsonb
        );
        CREATE INDEX ix_audit_tenant ON audit_log (tenant_id);
        CREATE INDEX ix_audit_at ON audit_log (at);
        CREATE INDEX ix_audit_resource ON audit_log (resource_type, resource_id);
        """
    )

    # --- 1. entities -----------------------------------------------------
    _table("entities", """
        code varchar(60) NOT NULL,
        legal_name varchar(300) NOT NULL,
        display_name varchar(300),
        entity_type varchar(40) NOT NULL DEFAULT 'Company',
        cin varchar(21),
        pan varchar(10),
        gstin varchar(15),
        sector varchar(60),
        sub_sector varchar(120),
        lens varchar(20),
        state varchar(60),
        location varchar(200),
        register_status varchar(40),
        promoter_group_code varchar(60),
        about text,
        toi text,
        notes text,
        tags jsonb,
        CONSTRAINT entities_tenant_code UNIQUE (tenant_id, code)
    """)
    op.execute("CREATE INDEX ix_entities_tenant_sector ON entities (tenant_id, sector);")
    op.execute("CREATE INDEX ix_entities_tenant_cin ON entities (tenant_id, cin);")
    op.execute("CREATE INDEX ix_entities_promoter_group ON entities (tenant_id, promoter_group_code);")
    op.execute("CREATE INDEX ix_entities_legal_name_trgm ON entities USING gin (legal_name gin_trgm_ops);")
    op.execute("CREATE INDEX ix_entities_tags ON entities USING gin (tags);")

    # --- people ----------------------------------------------------------
    _table("people", """
        name varchar(120) NOT NULL,
        full_name varchar(200) NOT NULL,
        role varchar(30) NOT NULL,
        email varchar(200),
        phone varchar(30),
        geography varchar(120),
        sectors varchar(300),
        started_on date,
        reports_to varchar(200),
        inactive boolean NOT NULL DEFAULT false,
        notes text,
        CONSTRAINT people_tenant_full_name UNIQUE (tenant_id, full_name)
    """)

    # --- counterparties --------------------------------------------------
    _table("counterparties", """
        name varchar(200) NOT NULL,
        short_name varchar(60),
        counterparty_type varchar(40),
        is_active boolean NOT NULL DEFAULT true,
        sectors varchar(400),
        ticket_min_cr numeric(14,2),
        ticket_max_cr numeric(14,2),
        notes text,
        CONSTRAINT counterparties_tenant_name UNIQUE (tenant_id, name)
    """)
    op.execute("CREATE INDEX ix_counterparties_type ON counterparties (tenant_id, counterparty_type);")

    # --- 2. deals --------------------------------------------------------
    _table("deals", """
        deal_no varchar(40),
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
        code varchar(60),
        product_type varchar(60),
        is_lending boolean NOT NULL DEFAULT false,
        is_syndication boolean NOT NULL DEFAULT false,
        is_asset_mon boolean NOT NULL DEFAULT false,
        rm varchar(120),
        analyst varchar(120),
        stage varchar(60),
        temperature varchar(10),
        source varchar(40),
        source_detail varchar(200),
        source_name varchar(200),
        date_received date,
        ic_date date,
        sanction_date date,
        disbursement_date date,
        exit_date date,
        remarks text,
        CONSTRAINT deals_tenant_deal_no UNIQUE (tenant_id, deal_no)
    """)
    op.execute("CREATE INDEX ix_deals_tenant_entity ON deals (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_deals_entity_fk ON deals (entity_id);")
    op.execute("CREATE INDEX ix_deals_code ON deals (tenant_id, code);")

    # --- leads -----------------------------------------------------------
    _table("leads", """
        lead_no varchar(40),
        entity_id uuid REFERENCES entities(id) ON DELETE SET NULL,
        company varchar(300) NOT NULL,
        sector varchar(60),
        lens varchar(20),
        source varchar(40),
        source_name varchar(200),
        rm varchar(120),
        status varchar(20) NOT NULL DEFAULT 'Active',
        temperature varchar(10),
        contact varchar(200),
        designation varchar(120),
        phone varchar(40),
        last_interaction_date date,
        next_action text,
        next_action_date date,
        converted_deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        conv varchar(120),
        notes text,
        CONSTRAINT leads_tenant_lead_no UNIQUE (tenant_id, lead_no)
    """)
    op.execute("CREATE INDEX ix_leads_tenant_status ON leads (tenant_id, status);")
    op.execute("CREATE INDEX ix_leads_entity ON leads (entity_id);")

    # --- lending_tracker -------------------------------------------------
    _table("lending_tracker", """
        tracker_no varchar(40),
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        amount_cr numeric(14,2),
        rm varchar(120),
        analyst varchar(120),
        stage varchar(40),
        stage_updated_at date,
        sanction_date date,
        disbursed_amount numeric(14,2),
        disbursement_date date,
        pending_with varchar(20),
        remarks text,
        stage_history jsonb,
        CONSTRAINT lending_tracker_tenant_no UNIQUE (tenant_id, tracker_no)
    """)
    op.execute("CREATE INDEX ix_lending_tenant_entity ON lending_tracker (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_lending_tenant_stage ON lending_tracker (tenant_id, stage);")
    op.execute("CREATE INDEX ix_lending_entity_fk ON lending_tracker (entity_id);")

    # --- syndication_tracker ---------------------------------------------
    _table("syndication_tracker", """
        tracker_no varchar(40),
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        toi varchar(200),
        rm varchar(120),
        analyst varchar(120),
        lc varchar(120),
        priority varchar(10),
        status varchar(40),
        amount_cr numeric(14,2),
        line varchar(120),
        facility text,
        tenor varchar(20),
        mandate_status text,
        potential text,
        im_status varchar(40),
        sanctioned_lender text,
        ip_lender text,
        date_of_sanction date,
        month_of_sanction varchar(12),
        nature text,
        existing text,
        price text,
        syndication_type varchar(80),
        mandate_status3 varchar(40),
        pending_with varchar(20),
        remarks text,
        status_history jsonb,
        CONSTRAINT syndication_tracker_tenant_no UNIQUE (tenant_id, tracker_no)
    """)
    op.execute("CREATE INDEX ix_syn_tenant_entity ON syndication_tracker (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_syn_tenant_status ON syndication_tracker (tenant_id, status);")
    op.execute("CREATE INDEX ix_syn_entity_fk ON syndication_tracker (entity_id);")

    # --- syndication_lenders ---------------------------------------------
    _table("syndication_lenders", """
        syndication_id uuid NOT NULL REFERENCES syndication_tracker(id) ON DELETE CASCADE,
        counterparty_id uuid REFERENCES counterparties(id) ON DELETE SET NULL,
        lender_name varchar(200) NOT NULL,
        is_existing boolean NOT NULL DEFAULT false,
        status varchar(40),
        since date,
        response_date date,
        chased_date date,
        note text,
        status_history jsonb
    """)
    op.execute("CREATE INDEX ix_synlender_tenant_syn ON syndication_lenders (tenant_id, syndication_id);")
    op.execute("CREATE INDEX ix_synlender_syn_fk ON syndication_lenders (syndication_id);")
    op.execute("CREATE INDEX ix_synlender_tenant_status ON syndication_lenders (tenant_id, status);")

    # --- asset_monetisation ----------------------------------------------
    _table("asset_monetisation", """
        tracker_no varchar(40),
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        state varchar(60),
        indicative_value_cr numeric(14,2),
        size_mw numeric(12,2),
        nature varchar(40),
        deal_type varchar(80),
        investor text,
        investor_type varchar(60),
        status varchar(40),
        teaser_date date,
        notes text,
        CONSTRAINT asset_mon_tenant_no UNIQUE (tenant_id, tracker_no)
    """)
    op.execute("CREATE INDEX ix_am_tenant_entity ON asset_monetisation (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_am_tenant_status ON asset_monetisation (tenant_id, status);")

    # --- 3. financials (versioned) ---------------------------------------
    _table("financials", """
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        statement_type varchar(40) NOT NULL,
        period_type varchar(20),
        period_start date,
        period_end date NOT NULL,
        fiscal_year varchar(12),
        as_of_date date,
        version_no integer NOT NULL DEFAULT 1,
        is_current boolean NOT NULL DEFAULT true,
        provenance text,
        source_document_ref varchar(300),
        currency varchar(3) NOT NULL DEFAULT 'INR',
        is_consolidated boolean,
        is_audited boolean,
        scale varchar(20),
        revenue numeric(18,2),
        ebitda numeric(18,2),
        pat numeric(18,2),
        total_debt numeric(18,2),
        net_worth numeric(18,2),
        dscr numeric(8,3),
        data jsonb,
        CONSTRAINT financials_unique_version UNIQUE (tenant_id, entity_id, statement_type, period_end, version_no)
    """)
    op.execute("CREATE INDEX ix_financials_entity ON financials (tenant_id, entity_id);")
    op.execute(
        "CREATE INDEX ix_financials_entity_current ON financials (tenant_id, entity_id, is_current);"
    )
    # At most one current row per (entity, statement_type, period_end).
    op.execute(
        """
        CREATE UNIQUE INDEX uq_financials_one_current
        ON financials (tenant_id, entity_id, statement_type, period_end)
        WHERE is_current AND deleted_at IS NULL;
        """
    )

    # --- 4. contracts_assets ---------------------------------------------
    _table("contracts_assets", """
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        asset_type varchar(40) NOT NULL,
        title varchar(300),
        counterparty_id uuid REFERENCES counterparties(id) ON DELETE SET NULL,
        counterparty_name varchar(200),
        capacity_mw numeric(12,2),
        tariff numeric(10,4),
        location varchar(200),
        state varchar(60),
        start_date date,
        end_date date,
        tenor_years numeric(6,2),
        contract_value_cr numeric(14,2),
        status varchar(60),
        details jsonb
    """)
    op.execute("CREATE INDEX ix_contracts_tenant_entity ON contracts_assets (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_contracts_entity_fk ON contracts_assets (entity_id);")

    # --- 5. interactions (master table 5, "Touchpoints") -----------------
    # The single interaction/touchpoint record. Polymorphic subject (ATLAS refType/refId);
    # holds both the manual note and the full VOX-captured touchpoint.
    _table("interactions", """
        subject_type varchar(30) NOT NULL,
        subject_id uuid NOT NULL,
        entity_id uuid REFERENCES entities(id) ON DELETE CASCADE,
        deal_id uuid REFERENCES deals(id) ON DELETE CASCADE,
        syndication_lender_id uuid REFERENCES syndication_lenders(id) ON DELETE SET NULL,
        lender_name varchar(200),
        interaction_type varchar(60) NOT NULL,
        direction varchar(20),
        occurred_at timestamptz NOT NULL DEFAULT now(),
        summary varchar(300),
        notes text,
        outcome text,
        performed_by varchar(120),
        contact_name varchar(200),
        next_action text,
        next_action_date date,
        next_meeting_date date,
        transcript text,
        language varchar(20),
        gps_lat numeric(9,6),
        gps_lng numeric(9,6),
        location varchar(200),
        attendees jsonb,
        key_intel jsonb,
        next_steps jsonb,
        source_ref varchar(200),
        source varchar(20),
        attachments jsonb,
        meta jsonb
    """)
    op.execute("CREATE INDEX ix_interactions_subject_time "
               "ON interactions (tenant_id, subject_type, subject_id, occurred_at);")
    op.execute("CREATE INDEX ix_interactions_entity_time ON interactions (tenant_id, entity_id, occurred_at);")
    op.execute("CREATE INDEX ix_interactions_deal_time ON interactions (tenant_id, deal_id, occurred_at);")
    op.execute("CREATE INDEX ix_interactions_tenant_type ON interactions (tenant_id, interaction_type);")
    op.execute("CREATE INDEX ix_interactions_syn_lender ON interactions (tenant_id, syndication_lender_id);")

    # --- 6. external_intelligence ----------------------------------------
    _table("external_intelligence", """
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        intel_type varchar(40) NOT NULL,
        source varchar(120),
        signal varchar(10),
        title varchar(400),
        summary text,
        url text,
        observed_at timestamptz,
        pulled_at timestamptz,
        payload jsonb,
        acknowledged_by varchar(120),
        acknowledged_at timestamptz,
        is_dismissed boolean NOT NULL DEFAULT false
    """)
    op.execute("CREATE INDEX ix_extintel_tenant_entity ON external_intelligence (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_extintel_tenant_type ON external_intelligence (tenant_id, intel_type);")
    op.execute("CREATE INDEX ix_extintel_entity_fk ON external_intelligence (entity_id);")

    # --- 7. monitoring_reporting -----------------------------------------
    _table("monitoring_reporting", """
        entity_id uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        record_type varchar(40) NOT NULL,
        covenant_name varchar(200),
        due_date date,
        submitted_date date,
        on_time boolean,
        delay_days integer,
        security_created_within_days integer,
        extension_count integer,
        behavioural_score numeric(6,2),
        period varchar(20),
        status varchar(60),
        feeds_irg boolean NOT NULL DEFAULT true,
        target_value numeric(18,4),
        actual_value numeric(18,4),
        breached boolean,
        waiver_status varchar(60),
        details jsonb
    """)
    op.execute("CREATE INDEX ix_monitoring_tenant_entity ON monitoring_reporting (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_monitoring_tenant_type ON monitoring_reporting (tenant_id, record_type);")
    op.execute("CREATE INDEX ix_monitoring_entity_fk ON monitoring_reporting (entity_id);")

    _apply_row_level_security()


# Tables that carry tenant_id and should be RLS-scoped.
_RLS_TABLES = [
    "entities", "people", "counterparties", "deals", "leads", "lending_tracker",
    "syndication_tracker", "syndication_lenders", "asset_monetisation", "financials",
    "contracts_assets", "interactions", "external_intelligence", "monitoring_reporting",
]


def _apply_row_level_security() -> None:
    """Defence-in-depth: even if an application query forgets its tenant filter, the
    database refuses to return another tenant's rows. Policies key off the
    ``app.current_tenant`` GUC set per request. RLS is only *enforced* when
    REGISTER_ENFORCE_RLS turns it on for the connecting role; the policies are always
    present so turning it on is a one-line switch."""
    for tbl in _RLS_TABLES:
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {tbl}_tenant_isolation ON {tbl}
            USING (
                current_setting('app.current_tenant', true) IS NULL
                OR tenant_id = current_setting('app.current_tenant', true)::uuid
            )
            WITH CHECK (
                current_setting('app.current_tenant', true) IS NULL
                OR tenant_id = current_setting('app.current_tenant', true)::uuid
            );
            """
        )


def downgrade() -> None:
    for tbl in reversed([
        "monitoring_reporting", "external_intelligence", "interactions", "contracts_assets",
        "financials", "asset_monetisation", "syndication_lenders", "syndication_tracker",
        "lending_tracker", "leads", "deals", "counterparties", "people", "entities",
    ]):
        op.execute(f"DROP TABLE IF EXISTS {tbl} CASCADE;")
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE;")
    op.execute("DROP TABLE IF EXISTS idempotency_keys CASCADE;")
    op.execute("DROP TABLE IF EXISTS ref_values CASCADE;")
    op.execute("DROP TABLE IF EXISTS tenant_settings CASCADE;")
    op.execute("DROP TABLE IF EXISTS tenants CASCADE;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at() CASCADE;")
