"""Covenant definitions + EWS case lifecycle (Release-1 increment 8).

Revision ID: 0018
Revises: 0017
Create Date: 2026-08-01

Two tables and one index, one milestone:

* ``covenants`` — the covenant DEFINITION/schedule (per company, optionally bound to a
  deal / lending line): what is tested (a financial metric against a threshold, or a
  reporting/security obligation), how often, from when, and how severe a breach is.
  Definitions are configuration; the OBSERVATIONS stay in ``monitoring_reporting``
  (PRISM master table 7) — one row per period, generated by the recurring sweep.

* ``ews_cases`` — the early-warning-signal case file: triggered (from a covenant breach,
  a RED/AMBER intel signal, a lapsed waiver, or manually) → under investigation →
  escalated → closed with a disposition. Closed cases are FROZEN by trigger and can
  never be deleted; the same trigger source can never spawn duplicate cases
  (UNIQUE (tenant, source, source_ref)).

* a partial UNIQUE index on ``monitoring_reporting`` making the recurring generation
  idempotent: one covenant observation per (covenant, due date), enforced by the
  database — a sweep retry or two concurrent sweeps can never double-generate.

All tenant-scoped with fail-closed RLS, matching the existing governance tables.
"""

from __future__ import annotations

import os

from alembic import op

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None


def _truthy(v: str | None) -> bool:
    return (v or "").strip().lower() in {"1", "true", "yes", "on"}


def _enable_rls(table: str, policy: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
    op.execute(
        f"""
        CREATE POLICY {policy} ON {table}
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
        """
    )
    if _truthy(os.getenv("REGISTER_ENFORCE_RLS")):
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")


def _grant(table: str, privileges: str) -> None:
    # ``table``/``privileges`` are literal constants supplied by this migration (not user input).
    stmt = (
        "DO $$ BEGIN "  # noqa: S608
        "IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'register_app') THEN "
        f"EXECUTE 'GRANT {privileges} ON {table} TO register_app'; "
        "END IF; "
        "EXCEPTION WHEN insufficient_privilege THEN "
        f"RAISE NOTICE '{table} grant to register_app skipped.'; "
        "END $$;"
    )
    op.execute(stmt)


def upgrade() -> None:
    # -- Covenant definitions ------------------------------------------------
    op.execute(
        """
        CREATE TABLE covenants (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            entity_id     uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            deal_id       uuid REFERENCES deals(id) ON DELETE SET NULL,
            lending_id    uuid,
            name          varchar(200) NOT NULL,
            covenant_type varchar(30)  NOT NULL DEFAULT 'Financial',
            description   text,
            metric        varchar(60),
            operator      varchar(2),
            threshold     numeric(18,4),
            frequency     varchar(12) NOT NULL DEFAULT 'Quarterly',
            first_due_on  date NOT NULL,
            grace_days    integer NOT NULL DEFAULT 0,
            breach_severity varchar(12) NOT NULL DEFAULT 'Amber',
            is_active     boolean NOT NULL DEFAULT true,
            tenant_id  uuid        NOT NULL,
            version    integer     NOT NULL DEFAULT 1,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            created_by varchar(120),
            updated_by varchar(120),
            deleted_at timestamptz,
            CONSTRAINT covenants_type
                CHECK (covenant_type IN ('Financial', 'Reporting', 'Security', 'Other')),
            CONSTRAINT covenants_frequency
                CHECK (frequency IN ('OneTime', 'Monthly', 'Quarterly', 'SemiAnnual',
                                     'Annual')),
            CONSTRAINT covenants_operator
                CHECK (operator IS NULL OR operator IN ('>=', '<=', '>', '<', '=')),
            CONSTRAINT covenants_severity
                CHECK (breach_severity IN ('Amber', 'Red')),
            CONSTRAINT covenants_financial_shape CHECK (
                covenant_type <> 'Financial'
                OR (metric IS NOT NULL AND operator IS NOT NULL AND threshold IS NOT NULL))
        );
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_covenants_updated_at BEFORE UPDATE ON covenants
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )
    op.execute("CREATE INDEX ix_covenants_entity ON covenants (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_covenants_deal ON covenants (tenant_id, deal_id);")
    op.execute("CREATE INDEX ix_covenants_active ON covenants (tenant_id) "
               "WHERE is_active AND deleted_at IS NULL;")
    _enable_rls("covenants", "covenants_tenant_isolation")
    _grant("covenants", "SELECT, INSERT, UPDATE")

    # -- Recurring-generation idempotency (observations live in monitoring_reporting) --
    op.execute(
        """
        CREATE UNIQUE INDEX monitoring_covenant_period_unique
        ON monitoring_reporting (tenant_id, (details->>'covenant_id'), due_date)
        WHERE record_type = 'Covenant' AND details->>'covenant_id' IS NOT NULL;
        """
    )

    # -- EWS cases -----------------------------------------------------------
    op.execute(
        """
        CREATE TABLE ews_cases (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            entity_id  uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            deal_id    uuid REFERENCES deals(id) ON DELETE SET NULL,
            source     varchar(30)  NOT NULL,
            source_ref varchar(120) NOT NULL,
            severity   varchar(12)  NOT NULL DEFAULT 'Amber',
            title      varchar(300) NOT NULL,
            summary    text,
            status     varchar(24)  NOT NULL DEFAULT 'Open',
            opened_by  varchar(200),
            assigned_to varchar(200),
            assigned_at timestamptz,
            investigation_note text,
            escalated_by varchar(200),
            escalated_at timestamptz,
            escalation_note text,
            disposition varchar(30),
            closure_note text,
            closed_by  varchar(200),
            closed_at  timestamptz,
            workflow_id varchar(200),
            tenant_id  uuid        NOT NULL,
            version    integer     NOT NULL DEFAULT 1,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            created_by varchar(120),
            updated_by varchar(120),
            deleted_at timestamptz,
            CONSTRAINT ews_cases_severity CHECK (severity IN ('Amber', 'Red')),
            CONSTRAINT ews_cases_status
                CHECK (status IN ('Open', 'UnderInvestigation', 'Escalated', 'Closed')),
            CONSTRAINT ews_cases_source_dedupe UNIQUE (tenant_id, source, source_ref)
        );
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_ews_cases_updated_at BEFORE UPDATE ON ews_cases
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )
    op.execute("CREATE INDEX ix_ews_cases_entity ON ews_cases (tenant_id, entity_id);")
    op.execute("CREATE INDEX ix_ews_cases_open ON ews_cases (tenant_id, status) "
               "WHERE status <> 'Closed';")
    # A closed case is a FACT: frozen; never deleted (the audit trail cites it).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ews_case_guard() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'ews_cases rows cannot be deleted (close instead)';
            END IF;
            IF OLD.status = 'Closed' THEN
                RAISE EXCEPTION 'ews_cases row % is Closed and is frozen', OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_ews_case_guard
        BEFORE UPDATE OR DELETE ON ews_cases
        FOR EACH ROW EXECUTE FUNCTION ews_case_guard();
        """
    )
    _enable_rls("ews_cases", "ews_cases_tenant_isolation")
    _grant("ews_cases", "SELECT, INSERT, UPDATE")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS ews_cases CASCADE;")
    op.execute("DROP FUNCTION IF EXISTS ews_case_guard();")
    op.execute("DROP INDEX IF EXISTS monitoring_covenant_period_unique;")
    op.execute("DROP TABLE IF EXISTS covenants CASCADE;")
