apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docrag.secretName" . }}
  labels:
    {{- include "docrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.config.apiKeys | quote }}
  {{- if not .Values.qdrant.apiKey.existingSecret }}
  qdrant-api-key: {{ .Values.qdrant.apiKey.value | quote }}
  {{- end }}
  {{- if not .Values.sarvam.apiKey.existingSecret }}
  sarvam-api-key: {{ .Values.sarvam.apiKey.value | quote }}
  {{- end }}
