"""Covenant definitions + EWS cases (Release-1 increment 8).

* :class:`Covenant` — the covenant DEFINITION/schedule: what is tested, how often, from
  when, and how severe a breach is. Definitions are configuration; the OBSERVATIONS
  (one row per period, generated by the recurring sweep) live in
  ``monitoring_reporting`` (PRISM master table 7) with ``record_type='Covenant'`` and
  ``details.covenant_id`` pointing back here — a partial UNIQUE index makes generation
  idempotent per (covenant, due date).

* :class:`EwsCase` — the early-warning-signal case file:

      Open ──▶ UnderInvestigation ──▶ Escalated ──▶ Closed (disposition + note)
        └──────────────┴──────────────────┴────────▶ Closed

  Triggered from a covenant breach, a RED/AMBER intel signal, a lapsed waiver, or
  manually. The DB dedupes by (tenant, source, source_ref) — one trigger, one case —
  and freezes Closed rows (trigger; never deletable).
"""

from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Integer, Numeric, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import RegisterBase


class Covenant(RegisterBase):
    """One covenant obligation on a company (optionally bound to a deal / lending line)."""

    __tablename__ = "covenants"

    entity_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("entities.id", ondelete="CASCADE"),
        nullable=False)
    deal_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("deals.id", ondelete="SET NULL"))
    lending_id: Mapped[uuid.UUID | None] = mapped_column(PGUUID(as_uuid=True))

    name: Mapped[str] = mapped_column(String(200), nullable=False)
    covenant_type: Mapped[str] = mapped_column(
        String(30), nullable=False, default="Financial", server_default="Financial"
    )  # Financial / Reporting / Security / Other
    description: Mapped[str | None] = mapped_column(Text)

    # The financial test: metric OP threshold (e.g. dscr >= 1.20). NULL for a pure
    # reporting/security obligation (those just have a due date to honour).
    metric: Mapped[str | None] = mapped_column(String(60))
    operator: Mapped[str | None] = mapped_column(String(2))   # >= / <= / > / < / =
    threshold: Mapped[float | None] = mapped_column(Numeric(18, 4))

    frequency: Mapped[str] = mapped_column(
        String(12), nullable=False, default="Quarterly", server_default="Quarterly"
    )  # ref: Covenant Frequency
    # Nullable ON PURPOSE: a covenant entered at sanction may DEFER its schedule —
    # the first due date is stamped one cycle after the first confirmed disbursement
    # tranche (see app.api.lms), because that is when the obligation actually starts.
    first_due_on: Mapped[date | None] = mapped_column(Date, nullable=True)
    grace_days: Mapped[int] = mapped_column(Integer, nullable=False, default=0,
                                            server_default="0")
    breach_severity: Mapped[str] = mapped_column(
        String(12), nullable=False, default="Amber", server_default="Amber"
    )  # the EWS severity a breach opens with
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True,
                                            server_default="true")


class EwsCase(RegisterBase):
    """One early-warning case, deduped per trigger source and frozen once Closed."""

    __tablename__ = "ews_cases"
    __table_args__ = (
        UniqueConstraint("tenant_id", "source", "source_ref",
                         name="ews_cases_source_dedupe"),
    )

    entity_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("entities.id", ondelete="CASCADE"),
        nullable=False)
    deal_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("deals.id", ondelete="SET NULL"))

    source: Mapped[str] = mapped_column(String(30), nullable=False)
    # covenant / intel / waiver_expiry / manual
    source_ref: Mapped[str] = mapped_column(String(120), nullable=False)
    severity: Mapped[str] = mapped_column(String(12), nullable=False, default="Amber",
                                          server_default="Amber")  # Amber / Red
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    summary: Mapped[str | None] = mapped_column(Text)

    status: Mapped[str] = mapped_column(String(24), nullable=False, default="Open",
                                        server_default="Open")  # ref: EWS Status
    opened_by: Mapped[str | None] = mapped_column(String(200))
    assigned_to: Mapped[str | None] = mapped_column(String(200))
    assigned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    investigation_note: Mapped[str | None] = mapped_column(Text)
    escalated_by: Mapped[str | None] = mapped_column(String(200))
    escalated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    escalation_note: Mapped[str | None] = mapped_column(Text)
    disposition: Mapped[str | None] = mapped_column(String(30))  # ref: EWS Disposition
    closure_note: Mapped[str | None] = mapped_column(Text)
    closed_by: Mapped[str | None] = mapped_column(String(200))
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    workflow_id: Mapped[str | None] = mapped_column(String(200))  # the case's run, if any
