{{- if not .Values.register.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflows.secretName" . }}
  labels:
    {{- include "workflows.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.register.apiKey | quote }}
{{- end }}
