{{- if not .Values.datastore.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.secretName" . }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
type: Opaque
stringData:
  datastore-password: {{ .Values.datastore.password | quote }}
{{- end }}
