apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    {{- if .Values.console.enabled }}
    - port: {{ .Values.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
    {{- end }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
