{{- if not .Values.register.apiKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vocx.secretName" . }}
  labels:
    {{- include "vocx.labels" . | nindent 4 }}
type: Opaque
stringData:
  register-api-key: {{ .Values.register.apiKey.value | quote }}
{{- end }}
